apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: hola-mundo
          image: edygc1988/ejercicio2:1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio
spec:
  type: LoadBalancer
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
